### ISSUE TITLE
"Warning: Error in <-: 'names' attribute [1] must be the same length as the vector [0]"

### ISSUE THREAD

**Issue by julieflecheux** [marseille-proteomique/DIAgui#7]
Hi,
Thank you for developping DIAgui ! Very useful !

I have an error trying to get either the peptide or protein files : 
![image](https://github.com/user-attachments/assets/a5693b05-cb9c-4988-9a23-398eb1d48445)
 
Do you know where is the problem ?

Thanks

**Comment by SamGG** [comment]
Hi Julie. Thanks for your feedback. I didn't find this message in our code. I guess that it is in a call to an external package. I think @mgerault can solve it, but I don't know if he is available at the moment. It could be easier if you send me the input data to reproduce and investigate this error. You will find my mail on my github profile. Best.

**Comment by mgerault** [comment]
Hi Julie and @SamGG,
Sorry for the late reply Julie; this error is most likely due to a problem of names or bad assignment of gene/protein info that I didn't anticipate from specific data. I should have time to take care of this. As @SamGG said, it would be easier for us to reproduce and fix the error if you send us a sample of your input data, if possible.
Thanks in advance.
Best

**Comment by mgerault** [comment]
Hi @julieflecheux ,
The error was due to the fact that in your 25min report, the lowest PG p-value was greater than 0.01 (the default value for filtering) hence returning an empty data frame. I fixed that so that the app returns you an error saying that you be less stringent.

You can now update DIAgui and it should work, let me know how it goes.

**Comment by julieflecheux** [comment]
Hi @mgerault, I still have the same error after updating DIAgui

**Comment by SamGG** [comment]
Hi Julie,

I have just tried the updated version. Now when I use the 25min file, I got a warning instead of the previous. Below is a screenshot of my trial, and I think you should get the same warning.

I increased the version number in case your system did not notice the changes in DIAgui. Could you please reinstall DIAgui and let me know what is the installed version after reinstallation? Use `packageVersion("DIAgui")` and check that version is 1.4.4.

![image](https://github.com/user-attachments/assets/80c17972-7011-42ab-b0ff-796a34e4aa13)

**Comment by julieflecheux** [comment]
Ok It worked reinstalling DIAgui ! Thanks for your help !

**Comment by SamGG** [comment]
Great! I close the issue, but feel free to reopen it if the current problem occurs with another data file, or open a new issue if you encounter another problem.
